const adventure1 = ['You begin your adventure in the town of Ravenbrook. You eat a hearty meal, buy some potions, and then set off for your day of adventuring.',
 'You awake groggy in Port Hacklaun. You don\'t know what you did last night, but you are hungover as hell. You struggle to get up and get your pack on and belt done, then you trodd off down the road to the wilderness.', 
 'You awake from your slumber in blissful fairy fey den. Your mood is enchanted, and many whisps sing to you as you are carried down a cliff to safety, where you trodd on ahead with a spring in your step.', 
 'You are at your campsite in the lava fields of Domrune. You scavenge some crude obsidian tools you were making last night and begin trekking away from the mountain.', 
 'You descend from the Crusader\'s Pinnacle Fortress in the City of Amakhazus. You are blessed by a Knight Valiant who hands you a weathered prayer scroll to use as a last resort. You leave the city and march on.', 
 'You are on a road in the countryside when you are stopped by a Courier on a donkey. They hand you a royal decree from King Ghaul. You scavenge gold dust from the writing and insignia and keep it in a bottle for use in alchemy later. You continue down the road.', 
 'You emerge from the water in the middle of Lake Oris. A mermaid emerges beside you and hands you a mysterious conch. She touches you with a waters boon which immediately propels you to the nearest shore over 3 miles away. You dry off in the sun.', 
 'You escape from a black ooze whose insides had previously teleported you to a vacuum dimension. You gather some gold and treasures from its corpse and exit a small stone dungeon into the sunlight.', 
 'You awake floating down on a soft cloud. An angels\' choir is heard fading out from above you. You feel an intense burst of energy and purpose as you hit the ground and start sprinting through the forest to an exact location.', 
 'You awake in a field of cows. You hear many of them mooing, but one of them speaks words to you in a language you cannot understand. You feel a strange connection to this cow that is now fading. It trods off, and you gather yourself and exit the field, grabbing some sunflowers along the way.'];
 const adventure2 = ['You encounter a bandit squad along the road. They demand to check your bag for malachite which is precious in the region. You draw your sword and stand steady. One by one, they approach you with weapons high. You cut down each one with a different technique, sparing the lives of a few scrawny ones that look petrified. You tell them to remember your name and flee the valley. You loot some gold and potions from the corpses of a few.',
 'You are attacked by a horde of werebats along the road. You immediately shapeshift into a cougar when you hear them, and swipe upwards ferociously as you are mobbed. Many of their wings are torn, and they all limp away squealing. You realize that one of them bit you, and you suspect you may be turning soon. You are indifferent at the thought of your new potential form. There are worse fates than this.', 
 'You come across a small dungeon built into the ground in the middle of a forest. There are lit torches around. You descend. Each room you find contains a series of traps and hazards. You dodge an exploding fire elemental trap, sprint through a room with sedative fumes, and skillfully leap to the entrance of a wizard\'s secret door. You pick the lock and steal a number of scrolls, trinkets, and enchanted curios. Another day in the life of a thief.', 
 'You awake from a stupor, realizing that you were drugged and brought to a pirate\'s enclave. You use a fire cantrip to slowly burn through the rope cage you are suspended in. You grab a rope and swing on it, landing on a small dinghy that is filled with treasure and your possessions. Many pirates are alerted to the sound of jingling coins, but you quickly paddle away out of the cove and out of site. Unfortunately, the dinghy was damaged and full of holes. It sinks to the bottom of the bay with most of the treasure. You pilfered a ruby crown and some goblets before escaping on the beach.', 
 'You are suddenly teleported to the seat of the Infernal Prince of Aberrus. He stands a tall 18 feet, with charred red skin and curved, white-ash horns. He beckons you to be his bard and play the lute he found. You sense he means for you to be his slave-jester. You remember the chant of a Holy code which was instated as a punishment for Aberrus demons. You speak the words, and the Prince starts to go mad. He screams in pain and reluctantly portals you back to the surface where you were traveling. You are covered in soot.', 
 'You climb to the top of a redwood tree where you find a gryphon\'s nest, nearly 20 feet wide. There are several gryphon chicks inside that start squawking loudly with their mouths open. You offer one of them half of your last meal of baked potatoes. It swallows them whole, delighted. From your pack you reveal a small stasis wand which you use to freeze and preserve the chick in stasis, then you place it in your bag of holding. A piercing screech sounds from above as a mother-gryphon skyrockets down towards the nest. You slide down the trunk of the tree and narrowly avoid the mother, hiding in cave at the base of the tree that you scoped out earlier. You have possibly captured for yourself a legendary mount!', 
 'You encounter a wraith during the night. It is nearly impossible to see and incorporeal. One touch could kill you. You instinctually dodge away from the sound of its screams, making a run for an open clearing. It follows you, but constantly looks up, seemingly perturbed of the light of the full moon. You grab a magic mirror that you had packed away and angle it to magnify the moonlight. The wraith notices, and zooms directly towards you. You manage to angle the mirror in time, and the wrath evaporates. You are left with an emerald ectoplasm, which is exceedingly valuable and used in invisibility potions.', 
 'You encounter a gold-haired terrier puppy on the road. It whimpers and runs away from you, limping. You run after it; hopefully you can capture it and tend its wounds. If leads you to a cliff where you are ambushed by a witch. She squeals with delight and launches a red lightning bolt towards you. You dodge away, but it hits your backpack and knocks you down. Your throwing stars fall out of the bag next to you, so you throw three of them at the witch. Two of them hit her in the face, and one strikes her leg, causing her to flail around and then tumble down the cliff. You swiftly take her out. She clutches an inscribed magic sprig with the name "Jareth" on it. You point it at the puppy, and he returns to the shape of a small boy. He thanks you, grabs an iron key from the witch, and sprints away. You gather some rare herbs from her body and trot on.', 
 'You come across a small, magenta mage tower. You stand at the entrance, where a hex-shaped forcefield covers most of the tower. You throw a rock up at an exposed window. A wizard pops his head out and mutters something about how his forcefield isn\'t working. The forcefield turns off, and the front door magically springs open. You are greeted by a slightly irritated, but jovial and welcoming old man. He teaches you a cantrip which allows you to freeze water. You help him located his tome of protection spells, and he chants a renewed forcefield spell for his tower. He grants you a protection to his own spell which allows you to bypass the field. He hands you clear blue soul gem and asks you to bring him a spriggan soul. He thanks you for your help and your company, and you exit the tower', 
 'You see a minotaur with severely overgrown hooves stomping on a boulder and snarling. You ready your battleaxe and charge him with your weapon raised. You miss his body entirely, and your weapon strikes through his left hoof, slicing it clean and nicely near the base. He notices you and stops snarling. He takes a relaxed posture and holds out his other hoof to you on the ground. You are slightly perturbed, but you gently slam down on this hoof with your axe, causing another clean cut. The Minotaur moos with excitement and stomps around. It runs off into the forest. You begrudgingly pick up the heavy hoof-horns, hoping to sell them. The mintaur emerges once again from the forest, running at you with a gleaming enchanted sword. You ready your weapon and stand firm, but the beast slows down and kneels, offering you the sword. You accept.'];
 const adventure3 = ['You arrive at the mouth of the Archetalmus Volcanochasm. You see three red dragons circling ahead, with seven or more lava lizards trudging around the lava floes. You feel your destiny is to destroy the Scarlet-stone Orb which powers this unnatural formation. You set down the Iceforge Crystal which you were given and start playing your mermaid\'s flute. The siren\'s song you were taught summons forth a mighty storm, and the crystal empowers it into an Ice Storm, which rains down massive ice shards from the sky. The beasts within the Volcanochasm roar in anger. The lizards burrow into the lava and are held tight in cooled obsidian. One of the dragons is struck with ice, plunging into the chasm. The other two fly away. You see all the color of the volcano fade to black, and as the storm settles, there is peace an quiet in the valley once again. AVDVENTURE COMPLETE!',
 'You have tracked down the nefarious Countess Anatonia at an isolated mansion. There is a thunderstorm overhead. You burst open the front door, and you are greeted by the Countess standing atop a grand staircase, with her henchmen standing in line in the foyer. She laughs maniacally, and raises her arm with a swift motion. Her long fingernails hang, and her minions are motionless until the slightest downward movement of her index finger. They immediately charge. You strike down the first with your bow and arrow, hitting him in the leg and then the stomach as he collapes. The second foe gets within ten feet, but you skillfully launch an arrow into her head. She falls forward and plunges her dagger into your boot as she exhales her last breath. The third enemy throws two daggers at you, one grazes your cheek, and the other lands in your thigh. You chant a fire spell and cause an explosion in the air beside his face, and he screams as he falls to the ground. The last henchman has disappeared, but soon emerges behind a pillar to your left. He strikes you in the shoulder. Your armor absorbs most of it, but you are now bleeding from four wounds. You chant another spell which heats his blade, causing him to roar and drop the weapon. You stab him in the chest with a dagger, and he falls. The Countess has descended the stair and seems thrilled at the turn of events. There is so much spilled blood. She starts hovering and manipulates all the blood from around the room, pulling some directly from your veins. You try to resist, but you start to black out. The last thing you hear is her soft caress as she gently strokes your face. YOU ARE DEAD.', 
 'You see a large whale emerging from the surf. You spotted it from your vessel, but the whale has been cornered to this beach. You see an aura of glimmering white light surrounding the beast. It is still moving toward the shore and not stopping. You see the whale leap out of the water onto the shore, but it does not crash down. The sand gives way effortlessly like water. The whale is now swimming through the land. You veer your ship directly into the surf and launch yourself onto the land by swinging from a rope. The whale is getting away, but you have a plan. You use a grappling hook to get to the top of a nearby oak tree. You can see the whale, as it continues to swim through the land, jumping out every so often. You ready your bow with an enchanted black arrow. You fire the arrow, and it hits a small white crystal on the whale\'s crest, knocking it out. The whale\'s aura immediately fades, and it lands heavy on the land with a thud. It\'s a shame for the poor creature. You extract the crystal and head out. There are more of these void-touched creatures to investigate. ADVENTURE COMPLETE!', 
 'You were captured, and have been brought in chains to a colliseum. You and nine other combatants are being held in the ring without armor or weapons. The tournament organizer roars at the crowd, and they scream in delight at every sentence. He orders his brutes to break the chains, and each combatand is given a weapon. You are instructed to fight to the death. These are all civilians, farmers, tradesmen, no soldiers. You pick up the scythe you were given and test its weight. You hurl it into the air, and it strikes the organizer, slicing halfway through his neck. He plunges through the stands and into the ring, bleeding out. The brute guards start to seize their unchained foes, but most are overpowered. One of the guards thrusts a spear into you from behind. The rest of the foes are taken out, and the freed captives pick you up and carry you out into the streets. A cloaked faction shows up and tends to your wounds, but you will not make it. You are paraded around a small village, as the villagers chant your name. YOU ARE DEAD.', 
 'You find a slumbering ogre in the forest. It appears to be asleep atop a pile of treasures you recognize from a local lord\'s castle. You were tasked with retrieving the most valuable item, a painting of the lord\'s late wife. You slip some poison into the beast\'s mouth, but it immediately awakes enraged. You cast a slow spell which causes the already lumbering beast to move at snail\'s pace. You strike at it\'s weak points while it struggles to finish a single swing. It topples to the ground, breathing heavily. You finish it off with a stab to the brain. The treasures are yours to keep, per the Lord\'s request. The painting is returned, and the lord thanks you and instates you among his high court. ADVENTURE COMPLETE!', 
 'You are investigating a series of strange magical events and have come to an icy cave of the northern Bleakbarrow region. There are lit torches with odd colors, and you suspect cult activity. You hear strange popping sounds and magical noises, as the air shakes periodically as some spells are being cast. You enter the cave to see a decrepit hag and a black-robed sorcerer, parading drunk around an iron pot. They are shouting in infernal tongues and summoning random creatures which appear and are instantly annihilated. You have confirmed by his appearance that this sorcerer is a cult leader, the hag is recognizeable from a local town\'s descriptions, and the two of them are inebriated on magic moon-fairy wine (which is illegal). You get close enough to grab some wine, with you will use as evidence to summon the local forces to attack this cave. But you make a large crackling nose as you step on some ice. The hag shrieks and stares at you intensely. You can do nothing but hope she is merciful. She turns you into a frog and throws you into her pot. YOU ARE DEAD.', 
 'You awaken from a trance. You can see nothing but darkness, and a black-robed figure with a shimmering white light around them. They greet you and claim to be a spirit of redepmtion, sent to give you a choice to return to the world or pass to the afterlife. You choose to return, and your spirit is filled with energy, as if you have been given a legendary purpose. ADVENTURE COMPLETE!', 
 'You are caught between a giant wild boar and group of three cobalt assassins. You angered the boar by stumbling into its territory, and the assassins were tracking you and heard the commotion. Neither want you to leave alive. You sit cross-legged on the ground, chanting a quick ritual shield to protect you. Your enemies all strike the shield from both sides, their attacks bouncing off with little effect. You summon a black magic explosion which disintegrates two of the assassins and the boar. The final assassin runs away. You loot the assassin\'s contract and embark on a final quest to rid yourself of whoever is targeting you. ADVENTURE COMPLETE!', 
 'You find a druid grove where 5 druids sit in a circle. Each of them chamnts in rythym while the others hum in harmony. They begin speaking to you in alternating order, as if they are of one mind. They offer you a chance of natural enlightenment. You seem eagar to accept, so you sit down in the center of their circle. As you meditate, their humming grows louder, and you find yourself unable to move. You feel a blissful feeling wash over you from the ground up. Soon you notice there are roots sprouting which hold you to the ground. You also notice branches and leaves appearing through the skin of your arms and face. The roots are yours. You are becoming a tree. Soon, your legs have become hard wood and shoot into the ground. You feel one last monent of peace as your mind is lifed to the heavens. YOU ARE DEAD (sort of ).', 
 'You encounter a plague in a local village. There is no one that responds to your calls except a few limp bodies crawling around, growling in agony. You head to the center of the village where you see a purple and green-robed man chanting over a sack of grain. He must be the plaguemaster. You summon a rock elemental who starts barreling towards him. The robed figure shoots out a magical cursed-skull blast at your elemental, but it has little effect. The man tries to siphon the life of your summon to himself, but finds nothing as he is crushed into the ground. The culprit is dealt with, but the village remains tainted. You see no solution but to put these people out of their misery. This entire city must be purged. ADVENTURE COMPLETE!'];

function adventure() {
    console.log(adventure1[Math.floor(Math.random() * 10)]);
    console.log(adventure2[Math.floor(Math.random() * 10)]);
    console.log(adventure3[Math.floor(Math.random() * 10)]);
};

adventure();